version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    env_file: ./docker/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    env_file: ./docker/pgadmin.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: ../Docker/backend.dockerfile
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    env_file: ./docker/backend.env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend/ReactBMW
      dockerfile: ../../Docker/frontend.dockerfile  # Chemin vers le Dockerfile frontend

    ports:
      - "${FRONTEND_PORT:-8080}:8080"
    env_file: ./docker/frontend.env
    depends_on:
      - backend

volumes:
  postgres_data:
  pgadmin_data:
