version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: ./docker/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
      - communique_bdd

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file: ./docker/pgadmin.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./docker/pgadmin_servers.json:/pgadmin/servers.json
    depends_on:
      - postgres
    networks:
      - my_network

  backend:
    build:
      context: ./backend
      dockerfile: ../Docker/backend.dockerfile
    ports:
      - "3000:3000"
    env_file: ./docker/backend.env
    depends_on:
      - postgres
    networks:
      - communique_bdd

  frontend:
    build:
      context: ./frontend/ReactBMW
      dockerfile: ../../Docker/frontend.dockerfile  # Chemin vers le Dockerfile frontend

    ports:
      - "8080:8080"
    env_file: ./docker/frontend.env
    depends_on:
      - backend

volumes:
  postgres_data:
  pgadmin_data:

networks:
  my_network: {}  # Définition du réseau avec des accolades
  communique_bdd: {}  # Définition du réseau avec des accolades
